Ордерс статус сделать энамом.
StalnoyKapibar/HIB pull request #155
Opened 2020-05-07 18:17 UTC by orlovleo12

Ордерс статус сделать энамом.

2020-05-07 18:26 UTC, Corexis requested changes

2020-05-07 18:26 UTC, Corexis commented on src/main/java/com/project/controller/restcontroller/OrderController.java
> +import com.sun.xml.internal.ws.util.StringUtils;
Зачем?

2020-05-07 18:26 UTC, Corexis commented on src/main/java/com/project/model/StatusOrder.java
> +public enum StatusOrder {
либо Status либо OrderStatus

2020-05-08 15:22 UTC, orlovleo12 commented on src/main/java/com/project/controller/restcontroller/OrderController.java
> +import com.sun.xml.internal.ws.util.StringUtils;
исправил

2020-05-08 15:22 UTC, orlovleo12 commented on src/main/java/com/project/model/StatusOrder.java
> +public enum StatusOrder {
исправил

2020-05-08 15:56 UTC, merged