Load book
StalnoyKapibar/HIB pull request #68
Opened 2020-04-07 14:36 UTC by Stogov-A

Реализована возможность загрузки книги из файла .hib
Добавлены новые поля
Исправлены методы добавления изменения книг.

2020-04-07 14:55 UTC, Corexis requested changes

2020-04-07 14:55 UTC, Corexis commented on src/main/java/com/project/HIBParser/HibParser.java
> +            book.setName(initLocaleString(jsonNode.get("name")));
Можно воспользоваться builder для сборки книги

2020-04-07 14:55 UTC, Corexis commented on src/main/java/com/project/HIBParser/HibParser.java
> +        } catch (IOException e) {
Исключение кидает весь код обернутый в try catch? По возможности оберни только то, что кидает это исключение

2020-04-07 14:55 UTC, Corexis commented on src/main/java/com/project/dao/BookDAOImpl.java
> +        BookDTO bookDTO = new BookDTO();
Можно сделать через builder

2020-04-07 14:55 UTC, Corexis commented on src/main/java/com/project/dao/BookDAOImpl.java
> +        Book book = new Book();
Аналогично

2020-04-07 14:55 UTC, Corexis commented on src/main/java/com/project/model/Book.java
>      private Integer price;
Лучше Long

2020-04-07 14:55 UTC, Corexis commented on src/main/java/com/project/model/Order.java
> +                    cartItem.getBook().getDesc(),
Можно вынести книгу в переменную, а не постоянно вызывать геттер

2020-04-07 14:55 UTC, Corexis commented on src/main/java/com/project/model/Order.java
> +                    cartItem.getBook().getDesc(),
Можно сделать конструктор, принимающий книгу, а не эту простыню параметров

2020-04-07 14:55 UTC, Corexis commented on src/main/java/com/project/model/OrderDTO.java
> +                    cartItemDTO.getBook().getDesc(),
Аналогично

2020-04-07 14:55 UTC, Corexis commented on src/main/resources/static/js/editWelcome.js
> +                            html += `<td id='n${tmp_html.id}'>${ad}</td>`;
Тк никто не фронтер претензий особо нет, но упомяну.
Можно избавиться от конкатинации. Интерполяция это позволяет. И тут в принципе как-то странно все выводится с этими ифами

2020-04-07 14:55 UTC, Corexis commented on src/main/resources/static/js/editWelcome.js
> +                `<div class="row">` +
А вот тут конкатинация точно не нужна. От плюсиков бы избавиться.

2020-04-07 14:55 UTC, Corexis commented on src/main/resources/static/js/editWelcome.js
> +    $("#myImage").attr("src", ``);
JQuery селекторы необходимо выносить в let переменные в начало документа, если ты обращаешься к ним более 1 раза.
Да и впринципе тут нужно разделить уже файл editWelcome на понятные несколько файлов.

2020-04-07 16:23 UTC, Stogov-A commented on src/main/java/com/project/HIBParser/HibParser.java
> +            book.setName(initLocaleString(jsonNode.get("name")));
сделано

2020-04-07 16:23 UTC, Stogov-A commented on src/main/java/com/project/HIBParser/HibParser.java
> +        } catch (IOException e) {
сделано

2020-04-07 16:38 UTC, Stogov-A commented on src/main/java/com/project/dao/BookDAOImpl.java
> +        BookDTO bookDTO = new BookDTO();
сделал

2020-04-07 16:38 UTC, Stogov-A commented on src/main/java/com/project/dao/BookDAOImpl.java
> +        Book book = new Book();
сделал

2020-04-07 16:39 UTC, Stogov-A commented on src/main/java/com/project/model/Book.java
>      private Integer price;
сделал

2020-04-08 07:24 UTC, Stogov-A commented on src/main/java/com/project/model/Order.java
> +                    cartItem.getBook().getDesc(),
класс не мой, но переделал на билдер.

2020-04-08 07:30 UTC, Stogov-A commented on src/main/java/com/project/model/OrderDTO.java
> +                    cartItemDTO.getBook().getDesc(),
сделал

2020-04-08 09:53 UTC, Stogov-A commented on src/main/resources/static/js/editWelcome.js
> +                `<div class="row">` +
исправил

2020-04-08 09:54 UTC, Stogov-A commented on src/main/resources/static/js/editWelcome.js
> +    $("#myImage").attr("src", ``);
разделил

2020-04-08 13:17 UTC, StalnoyKapibar reviewed
мержи

2020-04-08 13:17 UTC, StalnoyKapibar commented on src/main/java/com/project/HIBParser/HibParser.java
> +        List<Image>listImage = new ArrayList<>();
Пробел

2020-04-08 13:24 UTC, merged