Стили для адреса доставки
StalnoyKapibar/HIB pull request #95
Opened 2020-04-15 14:11 UTC by endddddd

оформил стили для адреса доставки

2020-04-15 14:53 UTC, DavidovArtem approved these changes

2020-04-16 02:43 UTC, Corexis requested changes

2020-04-16 02:43 UTC, Corexis commented on src/main/resources/static/js/shoppingcart.js
> +        '<div class="input-group-prepend  "><span class="input-group-text" id="basic-addon3">Country/Zip Code</span></div>' +
Замени на шаблонную строку ``

2020-04-17 06:36 UTC, Corexis commented on src/main/resources/static/js/shoppingcart.js
> +    let html = '';
а эта переменная нужна?

2020-04-17 06:36 UTC, Corexis commented on src/main/resources/static/js/shoppingcart.js
> +        "Country/Zip code" : order.address.country + " , " + order.address.postalCode,
шаблонные строки для кого)

2020-04-17 10:54 UTC, endddddd commented on src/main/resources/static/js/shoppingcart.js
> +    let html = '';
без неё выводиться последний результат, там же цикл

2020-04-17 12:44 UTC, merged